name: vakil99
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  delayed_display: ^2.0.0
  pin_code_fields: ^7.4.0
  loading_animation_widget: ^1.2.0+4
  rounded_loading_button: ^2.1.0
  group_radio_button: ^1.3.0
  bottom_bar_matu: ^1.3.1
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  razorpay_flutter: ^1.3.5
  lottie: ^2.7.0
  image_picker: ^1.0.7
  rolling_bottom_bar: ^0.2.2
  introduction_screen: ^3.1.12
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  auto_size_text: ^3.0.0
  http: ^1.2.0
  dartz: ^0.10.1
  gradient_borders: ^1.0.0
  calendar_date_picker2: ^0.5.3
  intl: ^0.19.0
  badges: ^3.1.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launch/calauncherapp.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/startuplist/
    - assets/images/trademark/
    - assets/images/goodser/
    - assets/images/intro/
    - assets/images/implink/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400